apiVersion: v1.1
pipelines:
  - name: Conan_App
    steps:
      - name: libA   
        type: DockerBuild
        configuration:
          dockerFileLocation: . 
          dockerFileName: Dockerfile
          dockerImageName: docker-dev-local.artifactory-eu.soleng-emea-staging.jfrog.team/build-liba
          dockerImageTag: ${run_number}
          dockerOptions: --build-arg build_name=${pipeline_name}  --build-arg build_number=${run_number}  --build-arg artifactory=http://artifactory-eu.soleng-emea-staging.jfrog.team/artifactory  --build-arg ci_user=${int_artSecret_user}  --build-arg apikey=${int_artSecret_apikey} --build-arg cfg_repo='https://github.com/conan-ci-cd-training/settings.git'  --build-arg art_repo=winter-conan  --build-arg up_pattern=* --build-arg component=libA 
          inputResources:
            - name: conan_pipeline_src
          integrations:
            - name: registry_eu
            - name: artSecret
        execution:
          onStart:
            - printenv int_artSecret_user
            - printenv int_artSecret_apikey
      - name: TestlibA 
        type: Bash
        configuration:
          inputSteps:
          - name: libA 
          integrations:
            - name: artSecret
        execution:
          onExecute:
            - echo "Testing ..." 
          onSuccess:
            - echo "Adding props..." 
            - curl -fL https://getcli.jfrog.io | sh &&  chmod 755 jfrog  
            - ./jfrog rt c --interactive=false --url=http://artifactory-eu.soleng-emea-staging.jfrog.team/artifactory --user=${int_artSecret_user} --apikey=${int_artSecret_apikey} art7 && ./jfrog rt use art7 && ./jfrog rt ping
            - curl -O https://raw.githubusercontent.com/cyan21/conan-pipeline/master/spec.json  
            - cat spec.json  
            - sed -i "s/#BUILD_NAME#/${pipeline_name}/" spec.json && sed -i "s/#BUILD_NUMBER#/${run_number}/" spec.json && cat spec.json 
            - ./jfrog rt sp "test=validated" --spec=spec.json
            - echo "Props Added !" 
#      - name: libB 
#        type: DockerBuild
#        configuration:
#          dockerFileLocation: . 
#          dockerFileName: Dockerfile
#          dockerImageName: docker-dev-local.artifactory-eu.soleng-emea-staging.jfrog.team/build-liba
#          dockerImageTag: ${run_number}
#          dockerOptions: --build-arg build_name=${pipeline_name}  --build-arg build_number=${run_number}  --build-arg artifactory=http://artifactory-eu.soleng-emea-staging.jfrog.team/artifactory  --build-arg ci_user=${int_artSecret_user}  --build-arg apikey=${int_artSecret_apikey} --build-arg cfg_repo='https://github.com/conan-ci-cd-training/settings.git'  --build-arg art_repo=winter-conan  --build-arg up_pattern=* --build-arg component=libB 
#          inputResources:
#            - name: conan_pipeline_src
#            - name: libA_build_info 
#          integrations:
#            - name: registry_eu
#            - name: artSecret
#        execution:
#          onStart:
#            - printenv int_artSecret_user
#            - printenv int_artSecret_apikey
